name: Hardhat Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hardhat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x] # استخدام الإصدارات المدعومة من Hardhat

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
